version: "3.8"
services:
  postgres:
    image: docker.io/library/postgres:latest
    environment:
      - "POSTGRES_DB=wise"
      - "POSTGRES_USER=system"
      - "POSTGRES_PASSWORD=klmn"
    volumes:
      - metiswisetestdb:/var/lib/postgresql/data
#    network_mode: "host"
  metiswise:
    image: metiswise:latest
    tty: true
    volumes:
      # TODO: Remove hugo-dependent volumes
      - type: bind
        source: ../
        target: /root/metiswise
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/data/hugo/repos:/repos
      - /mnt/data/hugo_bulk/scratch:/scratch
      - /home/hugo/.Xauthority:/root/.Xauthority
      #- "${XAUTHORITY:-$HOME/.Xauthority}:/home/metis/.Xauthority:ro"
    environment:
      - DISPLAY=${DISPLAY}
#    network_mode: "host"
  dbviewer:
    image: metiswise:latest
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /root/MetisWISE
    ports:
      - "127.0.0.1:8080:8080" # dbviewer
    environment:
      - DISPLAY=${DISPLAY}
    entrypoint: /root/MetisWISE/container/entrypoint_dbview.sh
#    network_mode: "host"
  jupyter:
    image: metiswise:latest
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /root/metiswise
    ports:
      - "127.0.0.1:8888:8888" # jupyter
    entrypoint: /root/MetisWISE/container/entrypoint_notebook.sh
#    network_mode: "host"
volumes:
  metiswisetestdb:
