[project]
name = "MetisWISE"
version = "0.0.4"
description = "MetisWISE"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Hugo Buddelmeijer", email="hugo@buddelmeijer.nl"},
]
maintainers = [
    {name = "Hugo Buddelmeijer", email="hugo@buddelmeijer.nl"},
]
classifiers=[
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = [
    # From https://pip.entropynaut.com/packages
    "commonwise",
    "metis-drld",
    "eso-pymetis",
    "dataserverwise",

    # Required for pycpl in pymetis: https://ivh.github.io/pycpl/simple/

    "astropy",
    "numpy",
    "matplotlib",
    "sphinx",
    "scipy",
    "pooch",
    "docutils",
    "httpx",
    "lxml",
    "httpcore",

    # TODO: Is there a benefit to using psycopg2 over psycopg2-binary?
    "psycopg2-binary",
    # "psycopg2",

    # TODO: Move some of these to optional dependency groups?
    "jupyter",

    # TODO: Move these to dev dependencies.
    "pytest",
    "coverage",
    "mock",

    # TODO: Move to build dependencies.
    "build",
]

[project.urls]
"Source" = "https://github.com/AstarVienna/MetisWISE"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["metiswise*"]

[tool.setuptools.package-data]
metiswise = ["config/Environment.cfg"]
